environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "6"
    - nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm config set loglevel warn
  - npm i -g npm
  - npm i

test_script:
  - npm test

build: off
